version: "3.9"

services:

  cpp:
    image: online_judge_cpp
    build:
      context: ./images
      dockerfile: Dockerfile.cpp


  c:
    image: online_judge_c
    build:
      context: ./images
      dockerfile: Dockerfile.c


  python:
    image: online_judge_python
    build:
      context: ./images
      dockerfile: Dockerfile.python


  javascript:
    image: online_judge_javascript
    build:
      context: ./images
      dockerfile: Dockerfile.javascript


  java:
    image: online_judge_java
    build:
      context: ./images
      dockerfile: Dockerfile.java